"""create: Measurement Table

Revision ID: 0f77305feac2
Revises: a5af120a189b
Create Date: 2026-08-11 22:16:16.036105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f77305feac2'
down_revision: Union[str, Sequence[str], None] = 'a5af120a189b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_tb',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('variable', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement_tb')
    # ### end Alembic commands ###
