"""create: Devices Table

Revision ID: d9dc47b036af
Revises: 
Create Date: 2026-08-13 20:08:18.402843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9dc47b036af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_tb',
    sa.Column('mac', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('mac')
    )
    op.create_table('slave_tb',
    sa.Column('mac', sa.String(), nullable=False),
    sa.Column('master', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['master'], ['master_tb.mac'], ),
    sa.PrimaryKeyConstraint('mac')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slave_tb')
    op.drop_table('master_tb')
    # ### end Alembic commands ###
